
library(readxl)
library(shiny)
library(ggplot2)

data <- read_excel("C:/Users/CHA/Desktop/haha/da.xlsx")

table(data$location)
table(data$metal)
table(data$`strip frame`)
table(data$carved)
table(data$`gesso moldings`)
table(data$`painted/stained`)
table(data$timber)
table(data$gilded)
table(data$`slip present`)
table(data$`no slip present`)
table(data$glazed)
table(data$glass)
table(data$perspex)
table(data$unglazed)
table(data$unglazed)
table(data$screweyes)
table(data$`unable to see reverse`)
table(data$`affixed to wall by`)
table(data$`two points`)
table(data$`one point`)
table(data$mirrorplates)
table(data$`not affixed to wall`)
table(data$`hanging system`)
table(data$screws)
table(data$`d-rings`)
table(data$`single strand wire`)
table(data$`multi strand wire`)
table(data$`no hanging system`)
table(data$`backing board`)
table(data$fomecor)
table(data$`no backing board`)
table(data$other)

